### PR TITLE
Update gazebo plugin to use planar_move

### PR DESCRIPTION
**Pull request by maxsvetlik**
While the current Gazebo plugin (force_based_move) works well for 3d simulations, the plugin does not accurately compute the transforms for non-differential based platforms.
As a result, the odometry output of the plugin is incorrect (in fact, there _is_ no odom output in the y direction) which is only noticeable in 2d simulation that depends on odometry for localization.

This PR changes the gazebo plugin to use planar_move, which has support for movement in x and y directions. The plugin has the quark of requiring high inertial values for the base, however, so these modified inertial values can be set through flags passed to vector_upload.

### CODE REVIEW

**Comment by maxsvetlik** [comment]
@PatrickHussey do you foresee a problem switching gazebo plugins? Was there a reason the hector_force_based_move plugin was initially chosen?

**Comment by PatrickHussey** [comment]
The forced based move plugin was chosen because the planar move plugin collisions are not realistic with actual inertial/mass values. 

They both have their caveats but the forced based move was better for simulating roll/pitch stability and collision.

Maybe using ground truth for odometry (or fake odometry) rather than the force-based move plugin output might be a solution.

Honestly I am not sure why the odometry from forced based move is off for you. We tested with ground truth from gazebo, and AMCL/gmapping and it seemed pretty good. Are you sure the sim timing is good? If you are trying to run a gazebo sim on slower hardware or a VM I have seen weird effects like this. I can run a quick test again. Just for reference the setup I have for gazebo testing:

Ubuntu 14.04 LTS
ROS Indigo with Gazebo 2.x 
i7 6950X 10-core @ 4.5GHz
64GB 3200 DDR4 
2x SLI NVIDIA 980Ti GPU

**Comment by maxsvetlik** [comment]
Thanks. My simulation time seems to match realtime closely enough. I am running modern hardware (and no VM) so I should be good there.

I've recorded the issue I'm seeing with force based move [here](https://drive.google.com/open?id=0B2MBLWE0lgOtZFlrRnhOUTJYMmc). In the video is RViz (with the stack launched with 2d_map_nav_demo.launch) and Gazebo from vector_gazebo/vector.launch. The map and demo world are the only additions to the otherwise clean/up-to-date workspace.

The issue is when y-velocity is being executed within 2d simulation. The force based move plugin does not publish y odometry outwardly, which is why the robot in RViz stayed stationary during y-movement. The move base goal will continue to be executed, despite that the gazebo model is actually moving. This disconnect happens any time the robot strafes.

It seems like a limitation of the plugin, so I would expect this issue to be widespread amongst non-diff drive robot models.

**Comment by PatrickHussey** [comment]
In your video the local odometry is working fine (walls represented by laser move relative to the robot in the map frame). I also ran the test and it works as expected. I think you have something else going on.

You either need to set the configuration to not use the platform odometry in vector_config.sh:
VECTOR_USE_PLATFORM_ODOMETRY=**false**
This will use robot_localization to generate the odom->base_link transform

or you need to update the forced based move controller in vector.urdf.xacro to publish the transform:
<publishOdometryTf>**1**</publishOdometryTf>
This will use gazebo ground truth to generate the odom->base_link transform

I am going to close this and open another issue so that when VECTOR_USE_PLATFORM_ODOMETRY=**true** then the force based move publishes the odometry topic automatically

**Comment by maxsvetlik** [comment]
I tried both of your suggestions. Unfortunately I am seeing the same end behaviour as in the posted video. I now believe I was previously setting VECTOR_USE_PLATFORM_ODOMETRY to false (the parameter defaulted, since my environment wasn't set). But for the sake of thoroughness, I reran the simulations with the suggested settings, verifying the tf_tree and environment variables. 

Using gazebo as the ground truth had the same issues with y-velocity commands, but also sent the robot model in a slight but constant turning motion across Z.

Other members of my team are experiencing the same issue, so I suspected this was widespread but apparently it is not. I'll keep this thread updated with any developments on our end

**Comment by PatrickHussey** [comment]
re-opening if it is still an issue. I cannot replicate the behavior so I will wait for more feedback.

**Comment by PatrickHussey** [comment]
what version of gazebo are you using? And just to verify; can you confirm you are using the master branch to test?

**Comment by maxsvetlik** [comment]
Yes, this is all using the latest master branch with Gazebo 2, ROS Indigo and Ubuntu 14.04.1

**Comment by PatrickHussey** [comment]
in your previous post you stated that the odom->base_link transform was not being published, and in the latest one you said it was being published, but maybe something is wrong with it.

Try just running:
`$ roslaunch vector_gazebo vector.launch`

Place some cylinders on the left/right and close enough to the robot so the laser can see them; then run:

`$ roslaunch vector_viz view_robot.launch function:=teleop`

Make sure the rviz frame is odom, and command y motion with the interactive marker while looking at the odometry output and the laser scan to see if everything looks like it is working correctly. You should see the odometry markers just move left and right following the robot, and the laser scan outline get further/closer away from the robot as you move left right. 

Then move the platform a known distance from the cylinder and see if gazebo and rviz match.

**Comment by PatrickHussey** [comment]
or just reproduce your video but set the frame to odom rather than map. 

It looks like the map->odom frame is not updating in your video which is why I pointed to an issue with AMCL not getting the odometry topic and/or the transform. You should be able to confirm with rqt_console, ros_wtf or rqt_graph.

Might be a clock thing too, make sure use_sim_time parameter is set system wide.

**Comment by maxsvetlik** [comment]
The odom->base_link transform is being published and I believe it actually behaves as it should. The issue is that the y-velocity Twist is not being published by force based move in the odometry it publishes out. The y-velocity odometry information is thus 0, causing the base_link not to update for any y-directional movements (because the odometry information is incorrect).

The laser scan, however, updates in 2d simulation because the model is moving inside the gazebo simulation. 

I'll take a look into your suggestions shortly

**Comment by maxsvetlik** [comment]
[Here](https://drive.google.com/open?id=0B2MBLWE0lgOtbVJkUTE3V21SWUk) is a video with RViz in the odom frame. Since I couldn't use move base in the odom frame (with point and click in rviz anyway) I teleoperated in: { +x, -x, -y, +y, +x, -x, -y, +y}.

The behavior is the same with the cylinders; y-velocity is 0 in the odometry published from gazebo.

**Comment by PatrickHussey** [comment]
You are right I just looked at the plugin code, it does not publish y for odometry.

I was using a version from source I had fixed that in. I think I may just add that modified plugin to the repo, rather than switch plugins due to the drawbacks of planar move related to inertial properties. 

What do you think?

**Comment by maxsvetlik** [comment]
Sure that sounds reasonable. Is your fix on a branch or fork of hector's gazebo repository at the moment?

**Comment by PatrickHussey** [comment]
No just locally, hence the confusion. I'll check it in shortly.

**Comment by PatrickHussey** [comment]
Added the new plugin in the latest commit. You should be able to check out the master, compile, run
terminal 1:
`roslaunch vector_gazebo vector.launch`
terminal 2:
`roslaunch vector_viz view_robot.launch`
terminal 3:
`rostopic echo /vector/odometry/local_filtered`

and verify the y odometry in sim is correct now. Please test and close if it works for you

**Comment by maxsvetlik** [comment]
Yes this works and resolves the issues I was seeing
Thanks for pulling that change into master!

**Pull request closed without merging**
