### PR TITLE
HLP-R repo merge

### PR DESCRIPTION
**Pull request by vchu**
Large merge of all changes made in the HLP-R repo for the specific packages "vector_description", "vector_gazebo", and "vector_ros"

"vector_description": Change the zero configuration of the arm to reflect the Kinova API standard

"vector_gazebo":
- Reorg the launch files
- Add in simulated world (simple room w/table and a small box)
- Conversion scripts that take vector msgs and converts into ros msgs for gazebo controllers
- Initialize script to setup the robot in ready position
- Controllers for the pan/tilt and linear actuator

"vector_ros": slight change to the teleop (vector_teleop_full_system.py") script. Puts in two changes that allows for the teleop to work in simulation.

### CODE REVIEW

**Comment by PeterMitrano** [comment]
What steps should be taken to test this? I'm planning to run the move it test you demonstrated earlier, as well as joystick teleop driving. There seem to be some new scripts (such as `body_part_setup` or `vector_control_interface`)

**Comment by vchu** [comment]
Good question. I think the plan you have (moveit and teleop) would be sufficient to test it out since the changes that would break the most things have to do with the arm.

For the `body_part_setup` and the `vector_control_interface` you should see the following behavior:

(1) when you launch the gazebo package using vector.launch, `body_part_setup` will move the linear actuator up and set the arm to a ready pose tuck.

(2) `vector_control_interface` is what converts the stanley messages from teleop into gazebo commands. So testing the teleop in gazebo will show that working.

Is it clear how to go about installing/testing everything? Otherwise, I can try to clean up all of the tutorials - but I'd prefer to do that once we have things merged.

**Comment by PeterMitrano** [comment]
yea keeping things separate (updating tutorials) work be better as a different PR. I'll comment back here if I have any issues.

**Comment by vchu** [comment]
I added in the moveit config package that works with the wpi_jaco_wrapper and decouples the linear actuator from the arm. To test this, it'll require the wpi_jaco_wrapper to be installed and working. 

@PeterMitrano, I think your previous test will cover this as well since you were planning on doing moveit. One thing to note - the launch file for the moveit tests is now in the moveit config package and not in the vector_gazebo launch folder. It is still named `vector_wpi_jaco_simple_moveit_sim.launch`

**Comment by PeterMitrano** [comment]
Ok, so on a first pass the arm and cameras don't show up which causes all sorts of issues elsewhere. Not sure if that's my fault or this PR yet

**Comment by vchu** [comment]
Hmm okay - I wasn't sure if it was my machine that was causing the issue because I saw this too and had never seen it previously.

I'll check in the fix that I used to fix it on my new machine. Basically I believe the culprit is the gain values from the plugin we use to simulate the omnibase. When I reduce the Z gain, then the arm and linear actuator doesn't explode. 

I don't think it is a permanent fix as I believe we still need to fix the mass and inertia values for the linear actuator, base, and pan/tilt unit, which will further prevent things from exploding (which makes the camera and arm disappear)

**Comment by vchu** [comment]
I forgot to mention that to make the simulator closer to the real robot behavior - you have to launch the remote teleop script in order to teleop the robot.  This will be added to the updated tutorial in the future.

`roslaunch vector_remote_teleop vector_remote_teleop.launch`

**Comment by PeterMitrano** [comment]
I'm planning to test this again tonight

**Comment by vchu** [comment]
Great. In testing, we also discovered that the linear actuator is way too unstable and the robot will tip over pretty easily. I went ahead and also added in some mass and inertia values that I pulled using SolidWorks and the CAD files.

They aren't perfect by any means, but they at least prevent the robot from freaking out and falling over as much.

**Comment by PeterMitrano** [comment]
So good news, arms and stuff show up fine. bad news, I still get errors. This one coming from somewhere in the move_group launch file. Any ideas? seems like a substitution error in some launch file or something.

```
Character [_] is not valid as the first character in Graph Resource Name [_planning/shape_transform_cache_lookup_wait_time]
```

**Comment by vchu** [comment]
I've never encountered that error before. This happens when you run `roslaunch vector_wpi_jaco_moveit_config vector_wpi_jaco_simple_moveit_sim.launch` ?

Ajinkya said he was able to install and run everything yesterday. @jainajinkya, can you chime in to confirm you tested the moveit arm launch file?

**Comment by PeterMitrano** [comment]
Yea, although I tracked it down to the "move_group" launch file. I'll take
another look tonight and see if I can figure out why. It's probably just
something I messed up

**Comment by vchu** [comment]
I'm going to move out some of the changes that we talked about that will go into HLP-R org. Specifically, the vector_gazebo changes and the moveit package. Then I think the rest of it should remain in this repo (vector_description and vector_ros) changes.

**Comment by vchu** [comment]
Nevermind - this is too messy. I'm going to go ahead and just start a new branch and just put the two small changes we want there.

**Pull request closed without merging**
